-- Criar schema se não existir
CREATE SCHEMA IF NOT EXISTS public;

-- Configurar UTF-8
SET client_encoding = 'UTF8';

-- Configurar timezone
SET timezone = 'America/Sao_Paulo';

-- =============================================
-- TABELAS
-- =============================================
-- -------------------------
-- Tabela: materiais
-- -------------------------
CREATE TABLE IF NOT EXISTS public.materiais (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    produto VARCHAR(200) NOT NULL,
    unidade_medida VARCHAR(20) NOT NULL,
    volume_embalagem NUMERIC(10,2) NOT NULL,
    preco_embalagem NUMERIC(10,2) NOT NULL,
    custo_unitario NUMERIC(10,6) GENERATED ALWAYS AS (preco_embalagem / volume_embalagem) STORED,
    observacoes VARCHAR(500),
    ativo BOOLEAN DEFAULT true NOT NULL,

    CONSTRAINT chk_materiais_volume CHECK (volume_embalagem > 0),
    CONSTRAINT chk_materiais_preco CHECK (preco_embalagem > 0)
);

-- -------------------------
-- Tabela: usuarios
-- -------------------------
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(50) NOT NULL DEFAULT 'VISUALIZADOR',
    ativo BOOLEAN DEFAULT true NOT NULL
);

-- =============================================
-- 5. TRIGGERS
-- =============================================

CREATE OR REPLACE FUNCTION public.trg_atualizar_custo_servico_material()
RETURNS TRIGGER AS $$
DECLARE
    v_custo NUMERIC;
BEGIN
    SELECT custo_unitario INTO v_custo
    FROM public.materiais
    WHERE id = NEW.material_id;

    NEW.custo_total := v_custo * NEW.quantidade_usada;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Tabela para a entidade Configuracoes

CREATE TABLE IF NOT EXISTS configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pretensao_salarial_mensal NUMERIC(14,2) NOT NULL,
    horas_semanais            NUMERIC(10,2) NOT NULL,
    semanas_media_mes         NUMERIC(10,4) NOT NULL DEFAULT 4.33,
    custo_fixo_pct            NUMERIC(7,4)  NOT NULL,
    margem_lucro_padrao_pct   NUMERIC(7,4)  NOT NULL,
    atualizado_em             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo                     BOOLEAN NOT NULL DEFAULT TRUE
);

-- Garantir que exista no máximo 1 registro ativo
-- Se você quiser permitir vários registros inativos e apenas 1 ativo:
CREATE UNIQUE INDEX IF NOT EXISTS uq_configuracoes_ativo_true
ON configuracoes ((ativo))
WHERE ativo IS TRUE;


-- =========================
-- ATIVIDADES
-- =========================
CREATE TABLE IF NOT EXISTS atividades (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(120) NOT NULL,
  cnae               VARCHAR(20)  NOT NULL,
  aliquota_total_pct NUMERIC(7,4) NOT NULL,  -- ex: 16.7700
  iss_pct            NUMERIC(7,4) NOT NULL,  -- ex: 2.8400
  observacao         VARCHAR(500),
  ativo              BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================
-- SERVICOS
-- =========================
CREATE TABLE IF NOT EXISTS servicos (
  id                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome                   VARCHAR(180) NOT NULL,
  grupo                  VARCHAR(80)  NOT NULL,
  duracao_minutos        INTEGER      NOT NULL,
  atividade_id           BIGINT       NOT NULL,
  margem_lucro_custom_pct NUMERIC(7,4),
  ativo                  BOOLEAN      NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_servico_atividade
    FOREIGN KEY (atividade_id) REFERENCES atividades (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);

-- =========================
-- PRECOS_PRATICADOS
-- =========================
CREATE TABLE IF NOT EXISTS precos_praticados (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  servico_id     BIGINT       NOT NULL,
  preco          NUMERIC(14,2) NOT NULL,
  vigencia_inicio DATE        NOT NULL,
  vigencia_fim    DATE,
  vigente        BOOLEAN      NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_preco_praticado_servico
    FOREIGN KEY (servico_id) REFERENCES servicos (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,

  CONSTRAINT ck_preco_praticado_vigencia
    CHECK (vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);

-- =========================
-- SERVICO_MATERIAIS (tabela de ligação)
-- =========================
CREATE TABLE IF NOT EXISTS servico_materiais (
  id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  servico_id       BIGINT       NOT NULL,
  material_id      BIGINT       NOT NULL,
  quantidade_usada NUMERIC(14,4) NOT NULL,

  CONSTRAINT fk_servico_material_servico
    FOREIGN KEY (servico_id) REFERENCES servicos (id)
    ON UPDATE RESTRICT
    ON DELETE CASCADE,

  CONSTRAINT fk_servico_material_material
    FOREIGN KEY (material_id) REFERENCES materiais (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,

  CONSTRAINT uk_servico_material
    UNIQUE (servico_id, material_id),

  CONSTRAINT ck_servico_materiais_quantidade
    CHECK (quantidade_usada > 0)
);


-- Inserir usuário administrador
INSERT INTO public.usuarios (nome, email, senha, perfil,  ativo)
VALUES (
    'Administrador',
    'admin@sistema.com',
    '$2a$10$es.zMEVd7ASaVWWXiKaceOnX7hoEm3wHgIL9d5UjgcfPDpGxqSQtK',
    'ADMIN',
    true
);

-- =============================================
-- MATERIAIS PARA ESTÉTICA FACIAL E MASSAGEM
-- =============================================

-- Limpeza de Pele e Facial
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Sabonete Facial Líquido', 'ml', 500.00, 85.00, 'Frasco de 500ml', true),
    ('Tônico Facial', 'ml', 500.00, 95.00, 'Frasco de 500ml', true),
    ('Esfoliante Facial', 'g', 500.00, 120.00, 'Pote de 500g', true),
    ('Máscara de Argila Verde', 'g', 500.00, 78.00, 'Pote de 500g', true),
    ('Máscara de Argila Branca', 'g', 500.00, 82.00, 'Pote de 500g', true);

-- Estética Facial
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Sérum Vitamina C', 'ml', 30.00, 145.00, 'Frasco de 30ml', true),
    ('Sérum Ácido Hialurônico', 'ml', 30.00, 165.00, 'Frasco de 30ml', true),
    ('Creme Anti-idade', 'g', 50.00, 185.00, 'Pote de 50g', true),
    ('Creme Hidratante Facial', 'g', 200.00, 125.00, 'Pote de 200g', true),
    ('Gel Clareador', 'g', 30.00, 98.00, 'Bisnaga de 30g', true),
    ('Ampola Ácido Hialurônico', 'ml', 60.00, 220.00, 'Caixa com 12 ampolas de 5ml', true);

-- Massagem Corporal
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Creme de Massagem Neutro', 'kg', 1.00, 68.00, 'Pote de 1kg', true),
    ('Gel Redutor', 'kg', 1.00, 145.00, 'Pote de 1kg', true),
    ('Gel Crioterápico', 'kg', 1.00, 125.00, 'Pote de 1kg', true),
    ('Loção Hidratante Corporal', 'l', 1.00, 65.00, 'Frasco de 1 litro', true);

-- Descartáveis e Higiene
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Lençol Descartável', 'm', 50.00, 85.00, 'Rolo com 50 metros', true),
    ('Touca Descartável', 'un', 100.00, 28.00, 'Pacote com 100 unidades', true),
    ('Máscara Descartável', 'un', 50.00, 45.00, 'Caixa com 50 unidades', true),
    ('Luvas de Procedimento', 'un', 100.00, 42.00, 'Caixa com 100 unidades', true),
    ('Algodão em Disco', 'un', 100.00, 18.00, 'Pacote com 100 discos', true),
    ('Gaze Estéril', 'un', 100.00, 55.00, 'Caixa com 100 unidades', true),
    ('Espátula Descartável', 'un', 100.00, 35.00, 'Pacote com 100 unidades', true),
    ('Toalha de Rosto Branca', 'un', 12.00, 180.00, 'Pacote com 12 toalhas', true);

-- Equipamentos Consumíveis
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Gel para Ultrassom', 'kg', 1.00, 68.00, 'Pote de 1kg', true),
    ('Gel Condutor Radiofrequência', 'kg', 1.00, 125.00, 'Pote de 1kg', true),
    ('Eletrodos Descartáveis', 'un', 50.00, 95.00, 'Pacote com 50 pares', true),
    ('Lâminas Dermaplaning', 'un', 10.00, 85.00, 'Caixa com 10 lâminas estéreis', true),
    ('Agulhas para Microagulhamento', 'un', 12.00, 180.00, 'Caixa com 12 cartuchos estéreis', true);

-- Hidratação e Finalização
INSERT INTO public.materiais (produto, unidade_medida, volume_embalagem, preco_embalagem, observacoes, ativo)
VALUES
    ('Máscara Hidratante Facial', 'un', 10.00, 120.00, 'Caixa com 10 máscaras de tecido', true),
    ('Máscara de Colágeno', 'un', 10.00, 145.00, 'Caixa com 10 máscaras', true),
    ('Água Termal', 'ml', 150.00, 58.00, 'Spray de 150ml', true);


INSERT INTO configuracoes (
    pretensao_salarial_mensal,
    horas_semanais,
    semanas_media_mes,
    custo_fixo_pct,
    margem_lucro_padrao_pct,
    atualizado_em,
    ativo
) VALUES (
    12000.00,        -- pretensão salarial mensal (12k)
    50.00,           -- horas semanais
    4.33,            -- semanas médias no mês
    12.0000,         -- custo fixo (%)
    20.0000,         -- margem de lucro padrão (%)
    CURRENT_TIMESTAMP,
    TRUE
);

-- =========================================================
-- INSERTS DE EXEMPLO (dados iniciais para “demo”)
-- Datas considerando hoje: 2026-01-29
-- =========================================================

-- Atividades (CNAE/Alíquotas) - exemplos
INSERT INTO atividades (nome, cnae, aliquota_total_pct, iss_pct, observacao, ativo)
VALUES
  ('Fisioterapia', '8650-0/04', 16.7700, 2.0000, 'Exemplo para serviços de fisioterapia.', TRUE),
  ('Estética / Tratamento de pele / Depilação e congêneres', '9602-5/02', 8.6300, 2.0000, 'Exemplo para serviços estéticos.', TRUE),
  ('Atividades físicas (Pilates / Treinamento)', '9313-1/00', 16.7700, 2.0000, 'Exemplo para atividades físicas.', TRUE);



-- Serviços - exemplos (amarrados às atividades)
-- Dica: aqui estou usando SELECT pelo nome da atividade pra ficar mais fácil no seed.
INSERT INTO servicos (nome, grupo, duracao_minutos, atividade_id, margem_lucro_custom_pct, ativo)
VALUES
  ('Drenagem Linfática Manual', 'Corporal', 60,
    (SELECT id FROM atividades WHERE nome = 'Fisioterapia' LIMIT 1),
    NULL, TRUE),

  ('Limpeza de Pele', 'Facial', 60,
    (SELECT id FROM atividades WHERE nome = 'Estética / Tratamento de pele / Depilação e congêneres' LIMIT 1),
    25.0000, TRUE),

  ('Microagulhamento', 'Facial', 60,
    (SELECT id FROM atividades WHERE nome = 'Estética / Tratamento de pele / Depilação e congêneres' LIMIT 1),
    30.0000, TRUE),

  ('Pilates (sessão)', 'Pilates', 50,
    (SELECT id FROM atividades WHERE nome = 'Atividades físicas (Pilates / Treinamento)' LIMIT 1),
    NULL, TRUE);




