-- Configurar UTF-8
SET client_encoding = 'UTF8';

-- Configurar timezone
SET timezone = 'America/Sao_Paulo';

-- =============================================
-- TABELAS
-- =============================================
-- -------------------------
-- Tabela: materiais
-- -------------------------
CREATE TABLE IF NOT EXISTS public.materiais (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    produto VARCHAR(200) NOT NULL,
    unidade_medida VARCHAR(20) NOT NULL,
    volume_embalagem NUMERIC(10,2) NOT NULL,
    preco_embalagem NUMERIC(10,2) NOT NULL,
    custo_unitario NUMERIC(10,6) GENERATED ALWAYS AS (preco_embalagem / volume_embalagem) STORED,
    observacoes VARCHAR(500),
    ativo BOOLEAN DEFAULT true NOT NULL,

    CONSTRAINT chk_materiais_volume CHECK (volume_embalagem > 0),
    CONSTRAINT chk_materiais_preco CHECK (preco_embalagem > 0)
);

-- -------------------------
-- Tabela: usuarios
-- -------------------------
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(50) NOT NULL DEFAULT 'VISUALIZADOR',
    ativo BOOLEAN DEFAULT true NOT NULL
);

-- Tabela para a entidade Configuracoes

CREATE TABLE IF NOT EXISTS configuracoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pretensao_salarial_mensal NUMERIC(14,2) NOT NULL,
    horas_semanais            NUMERIC(10,2) NOT NULL,
    semanas_media_mes         NUMERIC(10,4) NOT NULL DEFAULT 4.33,
    custo_fixo_pct            NUMERIC(7,4)  NOT NULL,
    margem_lucro_padrao_pct   NUMERIC(7,4)  NOT NULL,
    atualizado_em             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo                     BOOLEAN NOT NULL DEFAULT TRUE
);

-- Garantir que exista no máximo 1 registro ativo
-- Se você quiser permitir vários registros inativos e apenas 1 ativo:
CREATE UNIQUE INDEX IF NOT EXISTS uq_configuracoes_ativo_true
ON configuracoes ((ativo))
WHERE ativo IS TRUE;


-- =========================
-- ATIVIDADES
-- =========================
CREATE TABLE IF NOT EXISTS atividades (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(120) NOT NULL,
  cnae               VARCHAR(20)  NOT NULL,
  aliquota_total_pct NUMERIC(7,4) NOT NULL,  -- ex: 16.7700
  iss_pct            NUMERIC(7,4) NOT NULL,  -- ex: 2.8400
  observacao         VARCHAR(500),
  ativo              BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================
-- SERVICOS
-- =========================
CREATE TABLE IF NOT EXISTS servicos (
  id                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome                   VARCHAR(180) NOT NULL,
  grupo                  VARCHAR(80)  NOT NULL,
  duracao_minutos        INTEGER      NOT NULL,
  atividade_id           BIGINT       NOT NULL,
  margem_lucro_custom_pct NUMERIC(7,4),
  ativo                  BOOLEAN      NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_servico_atividade
    FOREIGN KEY (atividade_id) REFERENCES atividades (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);

-- =========================
-- PRECOS_PRATICADOS
-- =========================
CREATE TABLE IF NOT EXISTS precos_praticados (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  servico_id     BIGINT       NOT NULL,
  preco          NUMERIC(14,2) NOT NULL,
  vigencia_inicio DATE        NOT NULL,
  vigencia_fim    DATE,
  vigente        BOOLEAN      NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_preco_praticado_servico
    FOREIGN KEY (servico_id) REFERENCES servicos (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,

  CONSTRAINT ck_preco_praticado_vigencia
    CHECK (vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);

-- =========================
-- SERVICO_MATERIAIS (tabela de ligação)
-- =========================
CREATE TABLE IF NOT EXISTS servico_materiais (
  id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  servico_id       BIGINT       NOT NULL,
  material_id      BIGINT       NOT NULL,
  quantidade_usada NUMERIC(14,4) NOT NULL,

  CONSTRAINT fk_servico_material_servico
    FOREIGN KEY (servico_id) REFERENCES servicos (id)
    ON UPDATE RESTRICT
    ON DELETE CASCADE,

  CONSTRAINT fk_servico_material_material
    FOREIGN KEY (material_id) REFERENCES materiais (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,

  CONSTRAINT uk_servico_material
    UNIQUE (servico_id, material_id),

  CONSTRAINT ck_servico_materiais_quantidade
    CHECK (quantidade_usada > 0)
);






